version: '3.8'

services:
  adviso-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adviso_ai_fullstack
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: always
